name: release

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build and package extension
        run: bun run build:vsix

      - name: Publish to VS Marketplace
        run: bunx @vscode/vsce publish --packagePath *.vsix --pat ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX Registry
        run: bunx ovsx publish --packagePath *.vsix --pat ${{ secrets.OVSX_PAT }}

      - name: Upload VSIX to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          gh release upload "${TAG_NAME}" *.vsix
